#!/usr/bin/env groovy

GITHUB_CONTEXT = 'BCF-TERRAFORM-PROVIDER'

groovies = null

pipeline {
    agent { label 'docker-host' }
    options {
        buildDiscarder(
            logRotator(
                daysToKeepStr: '30',
                artifactDaysToKeepStr: '14'))
        timestamps()
    }
    stages {
        stage('Prepare Pipeline') {
            steps {
                script {
                    groovies = load 'jenkins/groovies'
                    groovies.setGitHubContextStatus(GITHUB_CONTEXT)
                    groovies.setup()
                }
            }
        }
        stage('Build') {
            steps {
                script { groovies.build() }
            }
            post {
                always {
                    script {
                        if (env.CHANGE_ID) {
                            groovies.linkAndPostApplianceDownloadUrls("")
                        }
                        groovies.archiveArtifacts()
                    }
                }
            }
        }
     }
    post {
        always {
            script {
                groovies.setResult()
                groovies.setGitHubContextStatus(GITHUB_CONTEXT)
                if (!env.CHANGE_ID) {
                    groovies.notifyThroughMailer()
                }
            }
        }
    }
}
